---
build_from:
    amd64: ghcr.io/hassio-addons/debian-base:7.8.3
    aarch64: ghcr.io/hassio-addons/debian-base:7.8.3
    armv7: ghcr.io/hassio-addons/debian-base:7.8.3
codenotary:
  base_image: codenotary@zolric.dev
  signer: codenotary@zolric.dev
