---
name: Zhome Jellyfin
version: v2.0
slug: zjellyfin
description: Streaming video
ingress: true
ingress_stream: true
panel_icon: mdi:television
panel_title: Jellyfin
init: false
hassio_api: true
homeassistant_api: true
host_network: true
host_dbus: true
ports: 
  8096/tcp: 8096
  8920/tcp: 8096
  1900/udp: 1900
  7359/udp: 7359
ports_description:
  8096/tcp: Web interface (Not required for Ingress) HTTP traffic
  8920/tcp: used by default for HTTPS traffic
  1900/udp: used for service auto-discovery, this is not configurable
  7359/udp: used for service auto-discovery, this is not configurable
arch:
  - aarch64
  - amd64
  - armv7
privileged: 
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - NET_ADMIN
full_access: true
hassio_role: admin
map:
  - addon_config:rw
  - media:rw
  - share:rw
options:
  disk_s: DATA
  type_s: null
schema:
  disk_s: str
  type_s: list(ntfs|ntfs-3g|ext4)?
startup: services
video: true
udev: true
backup_exclude:
  - "**/jellyfin/cache/**"
  - "**/jellyfin/logs/**"
  - "**/jellyfin/metadata/**"